### ISSUE TITLE
我怎么不能用

### ISSUE THREAD

**Issue by a2418701192** [Brush-JIM/YouXueYuan-Python#1]
我用了脚本不行
同时也用了73版的软件也发现不行

**Comment by Brush-JIM** [comment]
把软件拖到CMD或者PowerShell，回车运行，看看有什么提示，发一下。

**Comment by a2418701192** [comment]
Traceback (most recent call last):
  File "run.py", line 293, in <module>
NameError: name 'headless' is not defined
[13528] Failed to execute script run

**Comment by Brush-JIM** [comment]
Beta版已经修改了代码  
但是现在身边没电脑，没打包程序  
所以用脚本执行吧  
chromedriver.exe放在脚本同目录  
再试试

**Comment by a2418701192** [comment]
我用pycharm运行了一下发现只能输入账号，密码无法输入

**Comment by Brush-JIM** [comment]
密码输入我用了getpass模块  
刚刚查了一下  
Pycharm无法使用getpass模块

**Comment by a2418701192** [comment]
这个会自动登录优学库吗？

**Comment by a2418701192** [comment]
你怎么把Chromedriver打包进exe文件的的

**Comment by Brush-JIM** [comment]
修改spec文件（Pyinstaller打包会生成一个与脚本同名的spec文件，就是这个)  
将文件的内的  

> `binaries=[]`  

修改为  

> `binaries=[ ('chromedriver的路径\\chromedriver.exe', '.\\selenium\\webdriver') ]`    

保存，然后执行命令  

> `pyinstaller 刚刚修改的那个文件的名字.spec 脚本名字.py`  

如果打包chromedriver，那么selenium就不要写chromedriver路径，否则可能会说找不到chromedriver.exe  
方法来源 [https://stackoverflow.com/questions/39563851/how-to-include-chromedriver-with-pyinstaller](https://stackoverflow.com/questions/39563851/how-to-include-chromedriver-with-pyinstaller)   
那个回答有人回了两个疑问，是用“os.path.join”来实现，但是我已经用这个方法实现，所以就没试了

**Comment by Brush-JIM** [comment]
程序会保存账号密码，以及设置，还有cookie，这样就不用总是输账号密码

**Comment by a2418701192** [comment]
selenium不写chromedriver不会报错吗？

**Comment by a2418701192** [comment]
我这个为什么只能登陆，其他就没反应

**Comment by Brush-JIM** [comment]
selenium不写chromedriver的话，默认会从环境变量以及同目录下寻找chromedriver  
抱歉，因为Python版的问题太多了，现在打算重构

**Comment by a2418701192** [comment]
我的它并没有找到chromedriver反而爆了一大堆错误

**Comment by a2418701192** [comment]
作者加油

**Comment by Brush-JIM** [comment]
代码改好了，用脚本试试行不行吧

**Comment by a2418701192** [comment]
Traceback (most recent call last):
  File "run.py", line 332, in <module>
    else:
AttributeError: 'NoneType' object has no attribute 'string'
[3016] Failed to execute script run

提示错误

**Comment by Brush-JIM** [comment]
我好像发现不了问题，信息量有点少，是不是用程序执行，没用脚本执行？“Failed to execute script run”好像是Pyinstaller的问题  
试一试这个看看行不行[https://github.com/Brush-JIM/Test/blob/master/run.py](https://github.com/Brush-JIM/Test/blob/master/run.py)

**Comment by Brush-JIM** [comment]
[https://github.com/Brush-JIM/Test](https://github.com/Brush-JIM/Test)有run.py和run.exe，改进了代码，测试前最好删除同目录的data.json，如果出现问题，麻烦把显示的错误和同目录的debug_run.log发送至Brush-JIM@protonmail.com  
ths
